services:
  postgres:
    container_name: clinic-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: mDZkdL679o4K3vWESqS14r5iygVb20AS0Ii3McP2
      POSTGRES_DB: clinic
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql"

  rabbitmq:
    container_name: clinic-rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=clinic
      - RABBITMQ_DEFAULT_PASS=ZcRvCWoqP3c6doVeZ8euipSt6NzhWU63mklfxyC0C7hlzFveOD
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./log/:/var/log/rabbitmq/