services:
  postgres:
    container_name: clinic-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: mDZkdL679o4K3vWESqS14r5iygVb20AS0Ii3McP2
      POSTGRES_DB: clinic
    ports:
      - "5433:5432"
    volumes:
      - "./data:/var/lib/postgresql"